///////////////////////////////////////////////////////////////////
// Automatically generated by xml2ulxr v1.7.3.
//
// xml2ulxr is part of Ultra Lightweight XML RPC for C++.
// See also http://ulxmlrpcpp.sourceforge.net
//
// Intended for manual and persistent changes 
/////////////////////////////////////////////////

#ifndef UlxrIdlTest_names_H
#define UlxrIdlTest_names_H


// method names

// mapped to: void UlxrIdlTest::first_url4() (there are overloaded methods)
#define ULXR_CALLTO_UlxrIdlTest_first_url4_ovr4 \
  ULXR_PCHAR("UlxrIdlTest_first_url4_ovr4")

// mapped to: std::string * UlxrIdlTest::first_url4(int i) (there are overloaded methods)
#define ULXR_CALLTO_UlxrIdlTest_first_url4_ovr3 \
  ULXR_PCHAR("UlxrIdlTest_first_url4_ovr3")

// mapped to: std::string * UlxrIdlTest::first_url4(long int li) (there are overloaded methods)
#define ULXR_CALLTO_UlxrIdlTest_first_url4_ovr2 \
  ULXR_PCHAR("UlxrIdlTest_first_url4_ovr2")

// mapped to: const char * UlxrIdlTest::first_url4(float li) (there are overloaded methods)
#define ULXR_CALLTO_UlxrIdlTest_first_url4_ovr1 \
  ULXR_PCHAR("UlxrIdlTest_first_url4_ovr1")

// mapped to: wchar_t * const UlxrIdlTest::first_url4(double li) (there are overloaded methods)
#define ULXR_CALLTO_UlxrIdlTest_first_url4_ovr0 \
  ULXR_PCHAR("UlxrIdlTest_first_url4_ovr0")

// mapped to: std::string UlxrIdlTest::constTest() const
#define ULXR_CALLTO_UlxrIdlTest_constTest \
  ULXR_PCHAR("UlxrIdlTest_constTest")

// mapped to: std::string & UlxrIdlTest::constRefTest() const
#define ULXR_CALLTO_UlxrIdlTest_constRefTest \
  ULXR_PCHAR("UlxrIdlTest_constRefTest")

// mapped to: long int * UlxrIdlTest::firstViewConst() const
#define ULXR_CALLTO_UlxrIdlTest_firstViewConst \
  ULXR_PCHAR("UlxrIdlTest_firstViewConst")

// mapped to: std::string * UlxrIdlTest::firstView()
#define ULXR_CALLTO_UlxrIdlTest_firstView \
  ULXR_PCHAR("UlxrIdlTest_firstView")

// mapped to: std::wstring * UlxrIdlTest::nextView1(int i, long int * l, std::string & s, const bool * b, char c) const
#define ULXR_CALLTO_UlxrIdlTest_nextView1 \
  ULXR_PCHAR("UlxrIdlTest_nextView1")

// mapped to: std::basic_string<char> * UlxrIdlTest::nextView2(int i, long int l, std::string & s, bool * const b, char c) const
#define ULXR_CALLTO_UlxrIdlTest_nextView2 \
  ULXR_PCHAR("UlxrIdlTest_nextView2")

// mapped to: void UlxrIdlTest::getNumObjects(std::string s)
#define ULXR_CALLTO_UlxrIdlTest_getNumObjects \
  ULXR_PCHAR("UlxrIdlTest_getNumObjects")

// mapped to: const std::basic_string<wchar_t> * UlxrIdlTest::getObject(const std::string & s)
#define ULXR_CALLTO_UlxrIdlTest_getObject \
  ULXR_PCHAR("UlxrIdlTest_getObject")

// mapped to: int UlxrIdlTest::getNumPages(const std::wstring & s)
#define ULXR_CALLTO_UlxrIdlTest_getNumPages \
  ULXR_PCHAR("UlxrIdlTest_getNumPages")

// mapped to: const std::string * UlxrIdlTest::last_url4() (there are overloaded methods)
#define ULXR_CALLTO_UlxrIdlTest_last_url4_ovr0 \
  ULXR_PCHAR("UlxrIdlTest_last_url4_ovr0")

// mapped to: std::string * UlxrIdlTest::last_url4(int i) (there are overloaded methods)
#define ULXR_CALLTO_UlxrIdlTest_last_url4_ovr1 \
  ULXR_PCHAR("UlxrIdlTest_last_url4_ovr1")

// mapped to: std::string * UlxrIdlTest::last_url4(long int li) (there are overloaded methods)
#define ULXR_CALLTO_UlxrIdlTest_last_url4_ovr2 \
  ULXR_PCHAR("UlxrIdlTest_last_url4_ovr2")


#endif // UlxrIdlTest_H
