///////////////////////////////////////////////////////////////////
// Automatically generated by xml2ulxr v1.7.3.
//
// xml2ulxr is part of Ultra Lightweight XML RPC for C++.
// See also http://ulxmlrpcpp.sourceforge.net
//
// Intended for manual and persistent changes 
/////////////////////////////////////////////////

#ifndef UlxrIdlTestFuncs_names_H
#define UlxrIdlTestFuncs_names_H


// method names

// mapped to: void free_function1(int i) (there are overloaded methods)
#define ULXR_CALLTO_UlxrIdlTestFuncs_funcs__free_function1_ovr0 \
  ULXR_PCHAR("UlxrIdlTestFuncs_funcs__free_function1_ovr0")

// mapped to: long int free_function1(long int i, float f) (there are overloaded methods)
#define ULXR_CALLTO_UlxrIdlTestFuncs_funcs__free_function1_ovr1 \
  ULXR_PCHAR("UlxrIdlTestFuncs_funcs__free_function1_ovr1")

// mapped to: std::string * free_function2(long int * i, float f) (there are overloaded methods)
#define ULXR_CALLTO_UlxrIdlTestFuncs_inline_func__free_function2 \
  ULXR_PCHAR("UlxrIdlTestFuncs_inline_func__free_function2")


#endif // UlxrIdlTestFuncs_H
