; Script generated by the HM NIS Edit Script Wizard.

; HM NIS Edit Wizard helper defines
!define PRODUCT_NAME "Solipsis"
!define PRODUCT_VERSION "1.0.0"
!define PRODUCT_PUBLISHER "ANR-RIAM Project"
!define PRODUCT_WEB_SITE "http://www.solipsis.org"
!define PRODUCT_DIR_REGKEY "Software\Microsoft\Windows\CurrentVersion\App Paths\Navigator.exe"
!define PRODUCT_UNINST_KEY "Software\Microsoft\Windows\CurrentVersion\Uninstall\${PRODUCT_NAME}"
!define PRODUCT_UNINST_ROOT_KEY "HKLM"

; MUI 1.67 compatible ------
!include "MUI.nsh"

; MUI Settings
!define MUI_ABORTWARNING
!define MUI_ICON "${NSISDIR}\Contrib\Graphics\Icons\modern-install.ico"
!define MUI_UNICON "${NSISDIR}\Contrib\Graphics\Icons\modern-uninstall.ico"

; Welcome page
!insertmacro MUI_PAGE_WELCOME
; Directory page
!insertmacro MUI_PAGE_DIRECTORY
; Instfiles page
!insertmacro MUI_PAGE_INSTFILES
; Finish page
!define MUI_FINISHPAGE_SHOWREADME "$INSTDIR\navigator\readme.txt"
!insertmacro MUI_PAGE_FINISH

; Uninstaller pages
!insertmacro MUI_UNPAGE_INSTFILES

; Language files
!insertmacro MUI_LANGUAGE "English"

; MUI end ------

Name "${PRODUCT_NAME} ${PRODUCT_VERSION}"
OutFile "Setup.exe"
InstallDir "$PROGRAMFILES\Solipsis"
InstallDirRegKey HKLM "${PRODUCT_DIR_REGKEY}" ""
ShowInstDetails show
ShowUnInstDetails show

Section "Navigator" SEC01
  SetOutPath "$INSTDIR\navigator"
  File /r /x resources.cfg /x Ogre.cfg /x Ogre.log /x SOLlog.log /x *.pdb "..\..\Common\bin\navigator\Release\*.*"
  File "resources.cfg"
  CreateDirectory "$SMPROGRAMS\Solipsis"
  CreateShortCut "$SMPROGRAMS\Solipsis\Solipsis Navigator.lnk" "$INSTDIR\navigator\Navigator.exe"
  CreateShortCut "$DESKTOP\Solipsis Navigator.lnk" "$INSTDIR\navigator\Navigator.exe"
SectionEnd

Section "PeerSimulator" SEC02
  SetOutPath "$INSTDIR\peerSimulator"
  File /r /x resources.cfg /x Ogre.log /x *.pdb /x *.ilk "..\..\Common\bin\peerSimulator\Release\*.*"
  File "resources.cfg"
  CreateShortCut "$SMPROGRAMS\Solipsis\Solipsis PeerSimulator.lnk" "$INSTDIR\peerSimulator\peer.exe" "-h localhost -p 8550 -v 0 -s Deltastation1"
  CreateShortCut "$DESKTOP\Solipsis PeerSimulator.lnk" "$INSTDIR\peerSimulator\peer.exe" "-h localhost -p 8550 -v 0 -s Deltastation1"
SectionEnd

Section "Media" SEC03
  SetOutPath "$INSTDIR\Media"
  File /r /x .svn /x NaviLocal /x lua /x *.sif "..\..\Media\*.*"
SectionEnd

Section -AdditionalIcons
  SetOutPath $INSTDIR
  WriteIniStr "$INSTDIR\${PRODUCT_NAME}.url" "InternetShortcut" "URL" "${PRODUCT_WEB_SITE}"
  CreateShortCut "$SMPROGRAMS\Solipsis\Visit Solipsis homepage.lnk" "$INSTDIR\${PRODUCT_NAME}.url"
  CreateShortCut "$SMPROGRAMS\Solipsis\Uninstall.lnk" "$INSTDIR\uninst.exe"
SectionEnd

Section -Post
  WriteUninstaller "$INSTDIR\uninst.exe"
  WriteRegStr HKLM "${PRODUCT_DIR_REGKEY}" "" "$INSTDIR\navigator\Navigator.exe"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "DisplayName" "$(^Name)"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "UninstallString" "$INSTDIR\uninst.exe"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "DisplayIcon" "$INSTDIR\navigator\Navigator.exe"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "DisplayVersion" "${PRODUCT_VERSION}"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "URLInfoAbout" "${PRODUCT_WEB_SITE}"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "Publisher" "${PRODUCT_PUBLISHER}"
SectionEnd


Function un.onUninstSuccess
  HideWindow
  MessageBox MB_ICONINFORMATION|MB_OK "$(^Name) was successfully removed from your computer."
FunctionEnd

Function un.onInit
  MessageBox MB_ICONQUESTION|MB_YESNO|MB_DEFBUTTON2 "Are you sure you want to completely remove $(^Name) and all of its components?" IDYES +2
  Abort
FunctionEnd

Section Uninstall
  Delete "$INSTDIR\${PRODUCT_NAME}.url"
  Delete "$INSTDIR\uninst.exe"

  Delete "$SMPROGRAMS\Solipsis\Uninstall.lnk"
  Delete "$SMPROGRAMS\Solipsis\Website.lnk"
  Delete "$DESKTOP\Solipsis PeerSimulator.lnk"
  Delete "$SMPROGRAMS\Solipsis\Solipsis PeerSimulator.lnk"
  Delete "$DESKTOP\Solipsis Navigator.lnk"
  Delete "$SMPROGRAMS\Solipsis\Solipsis Navigator.lnk"

  RMDir "$SMPROGRAMS\Solipsis"
  RMDir /r "$INSTDIR\Media"
  RMDir /r "$INSTDIR\peerSimulator"
  RMDir /r "$INSTDIR\navigator"
  RMDir "$INSTDIR"

  DeleteRegKey ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}"
  DeleteRegKey HKLM "${PRODUCT_DIR_REGKEY}"
  SetAutoClose true
SectionEnd