#ifndef UlxrIdlTestFuncsUlxrServer_H
#define UlxrIdlTestFuncsUlxrServer_H

///////////////////////////////////////////////////////////////////
// Automatically generated by xml2ulxr v1.7.3.
//
// xml2ulxr is part of Ultra Lightweight XML RPC for C++.
// See also http://ulxmlrpcpp.sourceforge.net
//
// Don't edit manually unless you know what you are doing
///////////////////////////////////////////////////////////////////


//#define ULXR_UNICODE_ONLY_HELPERS
#include <ulxmlrpcpp/ulxmlrpcpp.h> // always first

namespace ulxr
{
  class MethodAdder;
}

void UlxrIdlTestFuncs_setupServerMethods(ulxr::MethodAdder &method_adder);

void UlxrIdlTestFuncs_removeServerMethods(ulxr::MethodAdder &method_adder);

#endif // UlxrIdlTestFuncsUlxrServer_H

